server:
  port: 80  #当前Eureka Client服务的端口

info:
  app:
    name: consumer-hello111  #当前服务在actuator监控中的应用名称

spring:
  application:
    name: consumer-hello  #当前服务注册在Eureka Server上的名称

#服务注册
eureka:
  instance:
    hostname: zyj.com  #主机名
    prefer-ip-address: true  #是否将当前服务的IP注册到 Eureka Server

  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/