server:
  port: 8888
spring:
  application:
    name: content-center
    #调用链监控
#  zipkin:
#    base-url: http://localhost:9411
#    discovery-client-enabled: false
#  sleuth:
#    sampler:
#      #抽样率，默认是0.1(10%)
#      probability: 1.0
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://39.97.254.106:3306/content_center?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    hikari:
      username: root
      password: abc.123
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        # 指定nacos server的地址
#        server-addr: 39.97.254.106:8848
        server-addr: 47.97.103.220:8848
#        namespace: 4beccfe1-5fa1-47df-844e-a57653467098
    sentinel :
      transport:
        #指定sentinel控制台地址
        dashboard: localhost:8080


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 基于配置的方法（随机策略）
user-center:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#饥饿加载（提升首次加载的性能）
ribbon:
  eager-load:
    enabled: true
    clients: user-center

logging:
  level:
    # feign的日志系统是建立在SpringBoot基础上的，此处一定要是debug，否则都不会打印
    com.soft1851.cententconter.feignclient.UserCenterFeignClient: debug

#消息队列，异步处理
rocketmq:
  name-server: 39.97.254.106:9876
#  name-server: 123.56.164.214:9876

  producer:
    #必须指定group
    group: test-group


# feign细粒度配置
#feign:
#  client:
#    config:
#      #想要调用的微服务名称
#      user-center:
#        loggerLevel: full
#feign:
#  sentinel:
#    # 为feign整合sentinel
#    enabled: true
#  client:
#    config:
#      # 全局配置
#      default:
#        loggerLevel: full
#        #配置feign的拦截器，让token可以在各个微服务之间传递
#        requestInterceptors:
#          - com.soft1851.cententconter.feignclient.interceptor.TokenInterceptor
#
#  httpclient:
#    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
#    enabled: true
#    # feign的最大连接数
#    max-connections: 200
#    # feign单个路径的最大连接数
#    max-connections-per-route: 50

jwt:
  secret: aaaaabbbbbcccccddddd
  #有效期，单位秒，默认两周
  expire-time-in-second: 1209600

feign:
  sentinel:
    # 为feign整合sentinel
    enabled: true
  client:
    config:
      # 全局配置
      default:
        loggerLevel: full
        # 配置feign的拦截器，让token可以在各个微服务之间的传递
        requestInterceptors:
          - com.soft1851.cententconter.feignclient.TokenInterceptor
  httpclient:
    # 让feign使用apache httpclient做请求；而不是默认的urlconnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50