server:
  port: 7001
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: zyj.com  #主机名
    prefer-ip-address: true    #是否将当前服务的IP注册到Eureka Server

  client:
    #是否要注册到其他Eureka Server实例
    register-with-eureka: false
    #是否从其他Eureka Server实例获取数据
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
